platform: nodejs_lib

profiles:
    pull-request:
        build_containers: [node8]
        publish_containers: [node8]
    component:
        build_containers: [node8]
        publish_containers: [node8]
shared:
    steps:
        update-version:
            bump_method: dynamic
        postinstall-deps: npm run install-subdirs
    settings:
        YNPM_THREE: 1
jobs:
    component:
        triggers: [sd@311249]