platform: nodejs_lib

profiles:
    pull-request:
        build_containers: [node8]
        publish_containers: [node8]
    component:
        build_containers: [node8]
        publish_containers: [node8]
shared:
    steps:
        update-version:
            bump_method: dynamic
        postinstall-deps: npm run install-subdirs
    settings:
        YNPM_THREE: 1
jobs:
    component:
        steps:
            postpublish:
                description: dist
                command: ynpm run postpublish        
        triggers: [sd@311249]

---
version: 4
shared:
  environment:
    SD_SETTING_YNPM_THREE: 1
    NODEJS_LIB_UPDATE_VERSION_BUMP_METHOD: dynamic

jobs:
  component:
    template: nodejs/lib@stable
    steps:
      - lint: echo DISABLED
      - posttest: cp -v $SD_SOURCE_DIR/artifacts/coverage/lcov.info $SD_ARTIFACTS_DIR/coverage/
      - postpublish: |
            if [ ! -z $SD_PULL_REQUEST ] ; then
              echo "Skipping DIST install"
            else
              npm run postpublish 
            fi
      - postinstall-deps: npm run install-subdirs
    requires:
      - ~commit
      - ~pr
